AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 Buckets and Lambda Functions for Workload Application using AWS SAM

Parameters:
  Environment:
    Type: String
    Default: Dev
    Description: Environment name for the VPC

Globals:
  Function:
    Runtime: python3.8
    Handler: index.lambda_handler
    Timeout: 30
    Tags:
      Environment: !Ref Environment

Resources:
  ### Lambda Execution Role ###
  PayPalProcessorLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PayPalProcessorLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        # Basic Lambda logging policy
        - PolicyName: BasicLambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"

        # DynamoDB Access Policy (optional if you still use DynamoDB)
        - PolicyName: DynamoDBAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:GetItem"
                  - "dynamodb:PutItem"
                  - "dynamodb:UpdateItem"
                  - "dynamodb:DeleteItem"
                  - "dynamodb:Scan"
                  - "dynamodb:Query"
                Resource: "arn:aws:dynamodb:*:*:table/AdminTable"

          # SSM Parameter Store Access Policy
        - PolicyName: SSMParameterAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ssm:GetParameter"
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/rcw-paypal-processor-gcp-service-account"
      Tags:
        - Key: Environment
          Value: !Ref Environment

  PayPalProcessorFunctionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      ContentUri: s3://rcw-code-bucket/paypal-processor/layer.zip

  ### Lambda Function for PayPal Processor ###
  PayPalProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PayPal-Processor
      Role: !GetAtt PayPalProcessorLambdaExecutionRole.Arn
      CodeUri: s3://rcw-code-bucket/paypal-processor/paypal-processor.zip
      Runtime: python3.8
      Layers:
      - !Ref PayPalProcessorFunctionLayer
      Tags:
        Environment: !Ref Environment
      Environment:
        Variables:
          SPREADSHEET_ID: 1Jpicnmuuuy7aS__mGb-3sLgED9vxvELrvffrDtOHWjo
          SERVICE_ACCOUNT_PARAMETER_NAME: rcw-paypal-processor-gcp-service-account

Outputs:
  PayPalProcessorLambdaFunctionArn:
    Value: !GetAtt PayPalProcessorFunction.Arn
    Description: "Lambda function ARN for PayPal Processor"